name: Build CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ani-sha/schemabuilder
          event-type: update-event